---
# Copyright (c) 2020 Contributors to Smart-Data-Models
# see https://github.com/smart-data-models/dataModel.ParksAndGardens


components: 
  schemas: 
    GreenspaceRecord: 
      $ref: "https://smart-data-models.github.io/dataModel.ParksAndGardens/GreenspaceRecord/model.yaml#/GreenspaceRecord"
info: 
  description: ""
  title: GreenspaceRecord
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: |
         This entity contains a harmonised description of the conditions recorded on
          a particular area or point inside a greenspace (flower bed, garden, etc.).
         This entity type has been inspired by the AgriParcelRecord entity type
         defined by the GSMA Harmonized Data Models.
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - GreenspaceRecord
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.ParksAndGardens/GreenspaceRecord/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.ParksAndGardens/GreenspaceRecord/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
