---
# Copyright (c) 2020 Contributors to Smart-Data-Models
# see https://github.com/smart-data-models/dataModel.ParksAndGardens


components: 
  schemas: 
    FlowerBed: 
      $ref: "https://smart-data-models.github.io/dataModel.ParksAndGardens/FlowerBed/model.yaml#/FlowerBed"
info: 
  description: ""
  title: FlowerBed
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: |
         A FlowerBed is a distinguishable planned space, usually outdoors, set aside for
          the display, cultivation, and enjoyment of plants and other forms of nature.
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - FlowerBed
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.ParksAndGardens/FlowerBed/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.ParksAndGardens/FlowerBed/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
